export const comingdummy = {
  dates: {
    maximum: "2025-09-10",
    minimum: "2025-08-20",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      genre_ids: [16, 28, 14, 53],
      id: 1311031,
      original_language: "ja",
      original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      overview:
        "The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
      popularity: 319.3282,
      poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
      release_date: "2025-07-18",
      title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      video: false,
      vote_average: 7.2,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      genre_ids: [14, 10751, 28, 12],
      id: 1087192,
      original_language: "en",
      original_title: "How to Train Your Dragon",
      overview:
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      popularity: 288.2539,
      poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
      release_date: "2025-06-06",
      title: "How to Train Your Dragon",
      video: false,
      vote_average: 8.023,
      vote_count: 1635,
    },
    {
      adult: false,
      backdrop_path: "/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg",
      genre_ids: [27, 9648],
      id: 1078605,
      original_language: "en",
      original_title: "Weapons",
      overview:
        "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
      popularity: 222.9006,
      poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
      release_date: "2025-08-04",
      title: "Weapons",
      video: false,
      vote_average: 7.626,
      vote_count: 382,
    },
    {
      adult: false,
      backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
      genre_ids: [16, 14, 12, 28],
      id: 980477,
      original_language: "zh",
      original_title: "哪吒之魔童闹海",
      overview:
        "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
      popularity: 188.2529,
      poster_path: "/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg",
      release_date: "2025-01-29",
      title: "Ne Zha 2",
      video: false,
      vote_average: 7.973,
      vote_count: 294,
    },
    {
      adult: false,
      backdrop_path: "/9whEVuKte4Qi0LI4TzPf7glinJW.jpg",
      genre_ids: [16, 10751, 14],
      id: 936108,
      original_language: "en",
      original_title: "Smurfs",
      overview:
        "When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him. With the help of new friends, the Smurfs must discover what defines their destiny to save the universe.",
      popularity: 204.9349,
      poster_path: "/8o6lkhL32xQJeB52IIG1us5BVey.jpg",
      release_date: "2025-07-05",
      title: "Smurfs",
      video: false,
      vote_average: 5.878,
      vote_count: 90,
    },
    {
      adult: false,
      backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
      genre_ids: [16, 10402, 28, 14, 35],
      id: 803796,
      original_language: "en",
      original_title: "KPop Demon Hunters",
      overview:
        "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
      popularity: 166.8446,
      poster_path: "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
      release_date: "2025-06-20",
      title: "KPop Demon Hunters",
      video: false,
      vote_average: 8.418,
      vote_count: 1021,
    },
    {
      adult: false,
      backdrop_path: "/nKyBbFSooRPTJVqjrDteD1lF733.jpg",
      genre_ids: [28, 12, 18],
      id: 1011477,
      original_language: "en",
      original_title: "Karate Kid: Legends",
      overview:
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      popularity: 149.5045,
      poster_path: "/AEgggzRr1vZCLY86MAp93li43z.jpg",
      release_date: "2025-05-08",
      title: "Karate Kid: Legends",
      video: false,
      vote_average: 7.158,
      vote_count: 678,
    },
    {
      adult: false,
      backdrop_path: "/sItIskd5xpiE64bBWYwZintkGf3.jpg",
      genre_ids: [28, 53, 80],
      id: 541671,
      original_language: "en",
      original_title: "Ballerina",
      overview:
        "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
      popularity: 117.9756,
      poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
      release_date: "2025-06-04",
      title: "Ballerina",
      video: false,
      vote_average: 7.433,
      vote_count: 1343,
    },
    {
      adult: false,
      backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
      genre_ids: [27, 9648],
      id: 574475,
      original_language: "en",
      original_title: "Final Destination Bloodlines",
      overview:
        "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
      popularity: 102.7754,
      poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
      release_date: "2025-05-14",
      title: "Final Destination Bloodlines",
      video: false,
      vote_average: 7.165,
      vote_count: 1953,
    },
    {
      adult: false,
      backdrop_path: "/5PJkK2iVXRO1ydrtgwuJdevmnOe.jpg",
      genre_ids: [37, 35, 80],
      id: 648878,
      original_language: "en",
      original_title: "Eddington",
      overview:
        "In May of 2020, a standoff between a small-town sheriff and mayor sparks a powder keg as neighbor is pitted against neighbor in Eddington, New Mexico.",
      popularity: 100.2607,
      poster_path: "/kg7lrTWGKyzLnj0E7BXl52nro1N.jpg",
      release_date: "2025-07-16",
      title: "Eddington",
      video: false,
      vote_average: 6.628,
      vote_count: 141,
    },
    {
      adult: false,
      backdrop_path: "/2DcD4Hh80SW7YVpwckkiEFRZX06.jpg",
      genre_ids: [28, 35],
      id: 1124619,
      original_language: "en",
      original_title: "Bride Hard",
      overview:
        "Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.",
      popularity: 88.7141,
      poster_path: "/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg",
      release_date: "2025-06-19",
      title: "Bride Hard",
      video: false,
      vote_average: 5.699,
      vote_count: 73,
    },
    {
      adult: false,
      backdrop_path: "/dcLV5rEXuQRW0ZlB7IMLArHMyWh.jpg",
      genre_ids: [35, 14, 10751],
      id: 1125257,
      original_language: "en",
      original_title: "Freakier Friday",
      overview:
        "Years after Tess and Anna endured an identity crisis, Anna now has a daughter of her own and a soon-to-be stepdaughter. As they navigate the myriad challenges that come when two families merge, Tess and Anna discover lightning might indeed strike twice.",
      popularity: 82.9101,
      poster_path: "/9wV65OmsjLAqBfDnYTkMPutXH8j.jpg",
      release_date: "2025-08-06",
      title: "Freakier Friday",
      video: false,
      vote_average: 6.869,
      vote_count: 88,
    },
    {
      adult: false,
      backdrop_path: "/odEEx7fS8GcZcZ5rEZnrrLsDIm7.jpg",
      genre_ids: [10751, 35, 80, 12, 16],
      id: 1175942,
      original_language: "en",
      original_title: "The Bad Guys 2",
      overview:
        "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
      popularity: 67.4951,
      poster_path: "/26oSPnq0ct59l07QOXZKyzsiRtN.jpg",
      release_date: "2025-07-24",
      title: "The Bad Guys 2",
      video: false,
      vote_average: 7.478,
      vote_count: 67,
    },
    {
      adult: false,
      backdrop_path: "/2IIKts2A9vnUdM9tTC76B8tDmuZ.jpg",
      genre_ids: [27],
      id: 1151031,
      original_language: "en",
      original_title: "Bring Her Back",
      overview:
        "Following the death of their father, a brother and sister are introduced to their new sibling by their foster mother, only to learn that she has a terrifying secret.",
      popularity: 66.8686,
      poster_path: "/tObSf1VzzHt9xB0csanFtb3DRjf.jpg",
      release_date: "2025-05-28",
      title: "Bring Her Back",
      video: false,
      vote_average: 7.5,
      vote_count: 559,
    },
    {
      adult: false,
      backdrop_path: "/wO15XEgeLbeijtf3MQAUqWCxSxc.jpg",
      genre_ids: [28, 35, 53],
      id: 1007734,
      original_language: "en",
      original_title: "Nobody 2",
      overview:
        "Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.",
      popularity: 59.9842,
      poster_path: "/iyxwxDZCpIm0vIORaHpmgJv2BGF.jpg",
      release_date: "2025-08-13",
      title: "Nobody 2",
      video: false,
      vote_average: 7.713,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
      genre_ids: [10749, 18],
      id: 1136867,
      original_language: "en",
      original_title: "Materialists",
      overview:
        "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
      popularity: 53.6748,
      poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
      release_date: "2025-06-12",
      title: "Materialists",
      video: false,
      vote_average: 6.679,
      vote_count: 349,
    },
    {
      adult: false,
      backdrop_path: "/yAqL0makiGke5yYiVWpmBDSKIVP.jpg",
      genre_ids: [27, 18, 53],
      id: 1278950,
      original_language: "en",
      original_title: "The Ritual",
      overview:
        "Two priests, one in crisis with his faith and the other confronting a turbulent past, must overcome their differences to perform a risky exorcism.",
      popularity: 50.0302,
      poster_path: "/uubL8yvtEBjz3V7DFQHjCuSQO8w.jpg",
      release_date: "2025-04-18",
      title: "The Ritual",
      video: false,
      vote_average: 5.831,
      vote_count: 139,
    },
    {
      adult: false,
      backdrop_path: "/1wi1hcbl6KYqARjdQ4qrBWZdiau.jpg",
      genre_ids: [35, 80, 28],
      id: 1035259,
      original_language: "en",
      original_title: "The Naked Gun",
      overview:
        "Only one man has the particular set of skills... to lead Police Squad and save the world: Lt. Frank Drebin Jr.",
      popularity: 48.162,
      poster_path: "/rmwQ8GsdQ1M3LtemNWLErle2nBU.jpg",
      release_date: "2025-07-30",
      title: "The Naked Gun",
      video: false,
      vote_average: 6.915,
      vote_count: 194,
    },
    {
      adult: false,
      backdrop_path: "/eNSUknQqzTXWE5EeT8ZnVccEPR0.jpg",
      genre_ids: [27, 53],
      id: 1285965,
      original_language: "en",
      original_title: "Dangerous Animals",
      overview:
        "A savvy and free-spirited surfer is abducted by a shark-obsessed serial killer. Held captive on his boat, she must figure out how to escape before he carries out a ritualistic feeding to the sharks below.",
      popularity: 46.6978,
      poster_path: "/9tk3Si960hg4E49eMt81dS7Qe9Z.jpg",
      release_date: "2025-06-05",
      title: "Dangerous Animals",
      video: false,
      vote_average: 6.5,
      vote_count: 159,
    },
    {
      adult: false,
      backdrop_path: "/u2ctOiURF9hL3hmXmEMHxcVPVrQ.jpg",
      genre_ids: [27],
      id: 1242011,
      original_language: "en",
      original_title: "Together",
      overview:
        "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
      popularity: 45.4429,
      poster_path: "/inliWt3ukcpKDGPpEe2lRDLwK2r.jpg",
      release_date: "2025-07-28",
      title: "Together",
      video: false,
      vote_average: 7.352,
      vote_count: 169,
    },
  ],
  total_pages: 64,
  total_results: 1266,
};
