export const trenddummy = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/yRBc6WY3r1Fz5Cjd6DhSvzqunED.jpg",
      id: 1061474,
      title: "Superman",
      original_title: "Superman",
      overview:
        "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
      poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [878, 12, 28],
      popularity: 911.0931,
      release_date: "2025-07-09",
      video: false,
      vote_average: 7.7,
      vote_count: 1945,
    },
    {
      adult: false,
      backdrop_path: "/nGrUZvMxVqJvW1VsJ3QZStxnsZN.jpg",
      id: 1254624,
      title: "Night Always Comes",
      original_title: "Night Always Comes",
      overview:
        "Facing eviction in a city her family can no longer afford, a woman plunges into a desperate and increasingly dangerous all-night search to raise $25,000.",
      poster_path: "/1jDo1nG7rtjaaQGpr6e73x9i9Xp.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [53, 18, 80],
      popularity: 112.9939,
      release_date: "2025-08-15",
      video: false,
      vote_average: 5.9,
      vote_count: 32,
    },
    {
      adult: false,
      backdrop_path: "/Q2OajDi2kcO6yErb1IAyVDTKMs.jpg",
      id: 1078605,
      title: "Weapons",
      original_title: "Weapons",
      overview:
        "When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.",
      poster_path: "/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [27, 9648],
      popularity: 222.9006,
      release_date: "2025-08-04",
      video: false,
      vote_average: 7.6,
      vote_count: 378,
    },
    {
      adult: false,
      backdrop_path: "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
      id: 1234821,
      title: "Jurassic World Rebirth",
      original_title: "Jurassic World Rebirth",
      overview:
        "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
      poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [878, 12, 28],
      popularity: 672.3469,
      release_date: "2025-07-01",
      video: false,
      vote_average: 6.37,
      vote_count: 1573,
    },
    {
      adult: false,
      backdrop_path: "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      id: 1087192,
      title: "How to Train Your Dragon",
      original_title: "How to Train Your Dragon",
      overview:
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [14, 10751, 28, 12],
      popularity: 288.2539,
      release_date: "2025-06-06",
      video: false,
      vote_average: 8.024,
      vote_count: 1631,
    },
    {
      adult: false,
      backdrop_path: "/a6bItEVaxgphpMswho1wVRerv4r.jpg",
      id: 7451,
      title: "xXx",
      original_title: "xXx",
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [28, 12, 53, 80],
      popularity: 107.6759,
      release_date: "2002-08-09",
      video: false,
      vote_average: 5.958,
      vote_count: 4513,
    },
    {
      adult: false,
      backdrop_path: "/9whEVuKte4Qi0LI4TzPf7glinJW.jpg",
      id: 936108,
      title: "Smurfs",
      original_title: "Smurfs",
      overview:
        "When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him. With the help of new friends, the Smurfs must discover what defines their destiny to save the universe.",
      poster_path: "/8o6lkhL32xQJeB52IIG1us5BVey.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [16, 10751, 14],
      popularity: 204.9349,
      release_date: "2025-07-05",
      video: false,
      vote_average: 5.878,
      vote_count: 90,
    },
    {
      adult: false,
      backdrop_path: "/5PJkK2iVXRO1ydrtgwuJdevmnOe.jpg",
      id: 648878,
      title: "Eddington",
      original_title: "Eddington",
      overview:
        "In May of 2020, a standoff between a small-town sheriff and mayor sparks a powder keg as neighbor is pitted against neighbor in Eddington, New Mexico.",
      poster_path: "/kg7lrTWGKyzLnj0E7BXl52nro1N.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [37, 35, 80],
      popularity: 100.2607,
      release_date: "2025-07-16",
      video: false,
      vote_average: 6.634,
      vote_count: 138,
    },
    {
      adult: false,
      backdrop_path: "/wO15XEgeLbeijtf3MQAUqWCxSxc.jpg",
      id: 1007734,
      title: "Nobody 2",
      original_title: "Nobody 2",
      overview:
        "Former assassin Hutch Mansell takes his family on a nostalgic vacation to a small-town theme park, only to be pulled back into violence when they clash with a corrupt operator, a crooked sheriff, and a ruthless crime boss.",
      poster_path: "/iyxwxDZCpIm0vIORaHpmgJv2BGF.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [28, 35, 53],
      popularity: 59.9842,
      release_date: "2025-08-13",
      video: false,
      vote_average: 7.632,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
      id: 1311031,
      title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
      original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      overview:
        "The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.",
      poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
      media_type: "movie",
      original_language: "ja",
      genre_ids: [16, 28, 14, 53],
      popularity: 319.3282,
      release_date: "2025-07-18",
      video: false,
      vote_average: 7.196,
      vote_count: 75,
    },
    {
      adult: false,
      backdrop_path: "/c9xmB53umjnrCMS4pZz11clF3yJ.jpg",
      id: 980477,
      title: "Ne Zha 2",
      original_title: "哪吒之魔童闹海",
      overview:
        "After a catastrophic event leaves their bodies destroyed, Ne Zha and Ao Bing are granted a fragile second chance at life. As tensions rise between the dragon clans and celestial forces, the two must undergo a series of perilous trials that will test their bond, challenge their identities, and decide the fate of both mortals and immortals.",
      poster_path: "/cb5NyNrqiCNNoDkA8FfxHAtypdG.jpg",
      media_type: "movie",
      original_language: "zh",
      genre_ids: [16, 14, 12, 28],
      popularity: 188.2529,
      release_date: "2025-01-29",
      video: false,
      vote_average: 7.973,
      vote_count: 294,
    },
    {
      adult: false,
      backdrop_path: "/2IIKts2A9vnUdM9tTC76B8tDmuZ.jpg",
      id: 1151031,
      title: "Bring Her Back",
      original_title: "Bring Her Back",
      overview:
        "Following the death of their father, a brother and sister are introduced to their new sibling by their foster mother, only to learn that she has a terrifying secret.",
      poster_path: "/tObSf1VzzHt9xB0csanFtb3DRjf.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [27],
      popularity: 66.8686,
      release_date: "2025-05-28",
      video: false,
      vote_average: 7.447,
      vote_count: 557,
    },
    {
      adult: false,
      backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
      id: 617126,
      title: "The Fantastic 4: First Steps",
      original_title: "The Fantastic 4: First Steps",
      overview:
        "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
      poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [878, 12],
      popularity: 168.0423,
      release_date: "2025-07-23",
      video: false,
      vote_average: 7.247,
      vote_count: 1000,
    },
    {
      adult: false,
      backdrop_path: "/7uzhHIEOJ3AliYICXLzTpQ4Rkrn.jpg",
      id: 537921,
      title: "Fixed",
      original_title: "Fixed",
      overview:
        "After learning he's getting neutered, a dog has 24 hours to squeeze in one last balls-to-the-wall adventure with the boys.",
      poster_path: "/9jpCvt6jrCKMCf3OCfZ0bM5mur3.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [16, 35],
      popularity: 46.6431,
      release_date: "2025-08-13",
      video: false,
      vote_average: 6.676,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: "/HI3LsIikSTjeQ3CuAkJq1SzlBT.jpg",
      id: 1422052,
      title: "Descendent",
      original_title: "Descendent",
      overview:
        "After a traumatic brain injury triggers terrifying visions of extraterrestrials and a newfound talent for drawing, a father-to-be begins to question his reality and becomes obsessed with the need to protect his family from an unseen threat.",
      poster_path: "/w3tg6Yf0Fwf8ScZWFscTVJtqXZ1.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [18, 27, 9648, 878],
      popularity: 12.5759,
      release_date: "2025-08-08",
      video: false,
      vote_average: 5,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/zav0v7gLWMu6pVwgsIAwt11GJ4C.jpg",
      id: 1100988,
      title: "28 Years Later",
      original_title: "28 Years Later",
      overview:
        "Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.",
      poster_path: "/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [27, 53, 878],
      popularity: 126.8553,
      release_date: "2025-06-18",
      video: false,
      vote_average: 6.8,
      vote_count: 1138,
    },
    {
      adult: false,
      backdrop_path: "/1Bavnm3tr5zJMAhBKKmGHVjbPZN.jpg",
      id: 1484453,
      title: "Snoopy Presents: A Summer Musical",
      original_title: "Snoopy Presents: A Summer Musical",
      overview:
        "Music and glee fill the air as Charlie Brown and the gang head off to summer camp. First-timer Sally doesn't get what all the hype is about. But when the camp may be forced to close, they team up to save it so more kids can make their own special memories.",
      poster_path: "/kK1ugxST3tCJZjZEO37sLb4Yot5.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [16, 10751],
      popularity: 26.1616,
      release_date: "2025-08-14",
      video: false,
      vote_average: 8,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      id: 986056,
      title: "Thunderbolts*",
      original_title: "Thunderbolts*",
      overview:
        "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
      poster_path: "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 86.5117,
      release_date: "2025-04-30",
      video: false,
      vote_average: 7.395,
      vote_count: 2215,
    },
    {
      adult: false,
      backdrop_path: "/1Lz0CmgukN8KyzxIn8gGe4NLV3D.jpg",
      id: 911430,
      title: "F1",
      original_title: "F1",
      overview:
        "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
      poster_path: "/9JePWGvgg1t4BOojyZEVQdOWjXO.jpg",
      media_type: "movie",
      original_language: "en",
      genre_ids: [28, 18],
      popularity: 76.2603,
      release_date: "2025-06-25",
      video: false,
      vote_average: 7.625,
      vote_count: 1030,
    },
    {
      adult: false,
      backdrop_path: "/dcpXPUVEqiuYclsnael3bJjos4B.jpg",
      id: 1280089,
      title: "The Siege at Thorn High",
      original_title: "Pengepungan di Bukit Duri",
      overview:
        "Edwin promised to his sister on her death bed to find her son she gave up long time ago. Edwin's quest brought him to become a substitute teacher in Duri High School, Jakarta, a school for juvenile delinquents. There he must face the most violent students to find his nephew. When he eventually finds the boy, a city-wide riot erupts and Edwin is trapped im the school with the cruel kids out for his blood.",
      poster_path: "/uis9PJkI6WHRczCumsfPFaaUAxm.jpg",
      media_type: "movie",
      original_language: "id",
      genre_ids: [28, 80, 53],
      popularity: 19.9722,
      release_date: "2025-04-17",
      video: false,
      vote_average: 8.4,
      vote_count: 19,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};
